Replace unzip utility with decompress (fixes #6)
jsforce/jsforce-metadata-tools pull request #7
Opened 2016-11-04 13:36 UTC by boxfoot

Fixes bug where large metadata zip files crash node by using a more robust unzip utility.

2016-11-30 16:26 UTC, boxfoot commented
@stomita any update on reviewing this PR?  Thanks!

2016-12-21 06:15 UTC, stomita requested changes

2016-12-21 06:15 UTC, stomita commented on package.json
> +    "readable-stream": "^2.0.2",
Several packages are downgraded and cannot pass the test

2016-12-21 15:49 UTC, boxfoot commented on package.json
> +    "readable-stream": "^2.0.2",
This has been addressed.

2017-06-29 09:24 UTC, merged